development:
  shop: luxehaar.com
  theme_id: '131025109085'
  password: b878bb9d100bf2827d15630bec860376
  theme_name: St-Luxehaar-store/main
  ignore_files: ['.sass-cache', '.git', 'node_modules', 'theme.zip', 'config.yml']

staging:
  shop: luxehaar.com
  theme_id: '131025109085'
  password: b878bb9d100bf2827d15630bec860376
  theme_name: St-Luxehaar-store/main
  ignore_files: ['.sass-cache', '.git', 'node_modules', 'theme.zip', 'config.yml']

production:
  shop: luxehaar.com
  theme_id: '131025109085'
  password: b878bb9d100bf2827d15630bec860376
  theme_name: St-Luxehaar-store/main
  ignore_files: ['.sass-cache', '.git', 'node_modules', 'theme.zip', 'config.yml']